In [1]:
import os
import glob
import pandas as pd
#set working directory
#os.chdir("Jan to Feb 2021")

In [2]:
#find all csv files in the folder 
#use glob pattern matching -> extension = 'csv'
#save result in list ->all_filenames

os.chdir("Oct to Dec 2020")
extension = 'csv'
all_filesnames20 = ["Oct to Dec 2020/"+i for i in glob.glob('*.{}'.format(extension))]

all_filesnames20

['Oct to Dec 2020/10-01-2020.csv',
 'Oct to Dec 2020/10-02-2020.csv',
 'Oct to Dec 2020/10-03-2020.csv',
 'Oct to Dec 2020/10-04-2020.csv',
 'Oct to Dec 2020/10-05-2020.csv',
 'Oct to Dec 2020/10-06-2020.csv',
 'Oct to Dec 2020/10-07-2020.csv',
 'Oct to Dec 2020/10-08-2020.csv',
 'Oct to Dec 2020/10-09-2020.csv',
 'Oct to Dec 2020/10-10-2020.csv',
 'Oct to Dec 2020/10-11-2020.csv',
 'Oct to Dec 2020/10-12-2020.csv',
 'Oct to Dec 2020/10-13-2020.csv',
 'Oct to Dec 2020/10-14-2020.csv',
 'Oct to Dec 2020/10-15-2020.csv',
 'Oct to Dec 2020/10-16-2020.csv',
 'Oct to Dec 2020/10-17-2020.csv',
 'Oct to Dec 2020/10-18-2020.csv',
 'Oct to Dec 2020/10-19-2020.csv',
 'Oct to Dec 2020/10-20-2020.csv',
 'Oct to Dec 2020/10-21-2020.csv',
 'Oct to Dec 2020/10-22-2020.csv',
 'Oct to Dec 2020/10-23-2020.csv',
 'Oct to Dec 2020/10-24-2020.csv',
 'Oct to Dec 2020/10-25-2020.csv',
 'Oct to Dec 2020/10-26-2020.csv',
 'Oct to Dec 2020/10-27-2020.csv',
 'Oct to Dec 2020/10-28-2020.csv',
 'Oct to Dec 2020/10-29-2020.csv',
 'Oct to Dec 2020/10-30-2020.csv',
 'Oct to Dec 2020/10-31-2020.csv',
 'Oct to Dec 2020/11-01-2020.csv',
 'Oct to Dec 2020/11-02-2020.csv',
 'Oct to Dec 2020/11-03-2020.csv',
 'Oct to Dec 2020/11-04-2020.csv',
 'Oct to Dec 2020/11-05-2020.csv',
 'Oct to Dec 2020/11-06-2020.csv',
 'Oct to Dec 2020/11-07-2020.csv',
 'Oct to Dec 2020/11-08-2020.csv',
 'Oct to Dec 2020/11-09-2020.csv',
 'Oct to Dec 2020/11-10-2020.csv',
 'Oct to Dec 2020/11-11-2020.csv',
 'Oct to Dec 2020/11-12-2020.csv',
 'Oct to Dec 2020/11-13-2020.csv',
 'Oct to Dec 2020/11-14-2020.csv',
 'Oct to Dec 2020/11-15-2020.csv',
 'Oct to Dec 2020/11-16-2020.csv',
 'Oct to Dec 2020/11-17-2020.csv',
 'Oct to Dec 2020/11-18-2020.csv',
 'Oct to Dec 2020/11-19-2020.csv',
 'Oct to Dec 2020/11-20-2020.csv',
 'Oct to Dec 2020/11-21-2020.csv',
 'Oct to Dec 2020/11-22-2020.csv',
 'Oct to Dec 2020/11-23-2020.csv',
 'Oct to Dec 2020/11-24-2020.csv',
 'Oct to Dec 2020/11-25-2020.csv',
 'Oct to Dec 2020/11-26-2020.csv',
 'Oct to Dec 2020/11-27-2020.csv',
 'Oct to Dec 2020/11-28-2020.csv',
 'Oct to Dec 2020/11-29-2020.csv',
 'Oct to Dec 2020/11-30-2020.csv',
 'Oct to Dec 2020/12-01-2020.csv',
 'Oct to Dec 2020/12-02-2020.csv',
 'Oct to Dec 2020/12-03-2020.csv',
 'Oct to Dec 2020/12-04-2020.csv',
 'Oct to Dec 2020/12-05-2020.csv',
 'Oct to Dec 2020/12-06-2020.csv',
 'Oct to Dec 2020/12-07-2020.csv',
 'Oct to Dec 2020/12-08-2020.csv',
 'Oct to Dec 2020/12-09-2020.csv',
 'Oct to Dec 2020/12-10-2020.csv',
 'Oct to Dec 2020/12-11-2020.csv',
 'Oct to Dec 2020/12-12-2020.csv',
 'Oct to Dec 2020/12-13-2020.csv',
 'Oct to Dec 2020/12-14-2020.csv',
 'Oct to Dec 2020/12-15-2020.csv',
 'Oct to Dec 2020/12-16-2020.csv',
 'Oct to Dec 2020/12-17-2020.csv',
 'Oct to Dec 2020/12-18-2020.csv',
 'Oct to Dec 2020/12-19-2020.csv',
 'Oct to Dec 2020/12-20-2020.csv',
 'Oct to Dec 2020/12-21-2020.csv',
 'Oct to Dec 2020/12-22-2020.csv',
 'Oct to Dec 2020/12-23-2020.csv',
 'Oct to Dec 2020/12-24-2020.csv',
 'Oct to Dec 2020/12-25-2020.csv',
 'Oct to Dec 2020/12-26-2020.csv',
 'Oct to Dec 2020/12-27-2020.csv',
 'Oct to Dec 2020/12-28-2020.csv',
 'Oct to Dec 2020/12-29-2020.csv',
 'Oct to Dec 2020/12-30-2020.csv',
 'Oct to Dec 2020/12-31-2020.csv']

In [3]:
os.chdir("../Jan to Feb 2021")
extension = 'csv'
all_filesnames21 = ["Jan to Feb 2021/"+i for i in glob.glob('*.{}'.format(extension))]

os.chdir("..")

all_filesnames21

['Jan to Feb 2021/01-01-2021.csv',
 'Jan to Feb 2021/01-02-2021.csv',
 'Jan to Feb 2021/01-03-2021.csv',
 'Jan to Feb 2021/01-04-2021.csv',
 'Jan to Feb 2021/01-05-2021.csv',
 'Jan to Feb 2021/01-06-2021.csv',
 'Jan to Feb 2021/01-07-2021.csv',
 'Jan to Feb 2021/01-08-2021.csv',
 'Jan to Feb 2021/01-09-2021.csv',
 'Jan to Feb 2021/01-10-2021.csv',
 'Jan to Feb 2021/01-11-2021.csv',
 'Jan to Feb 2021/01-12-2021.csv',
 'Jan to Feb 2021/01-13-2021.csv',
 'Jan to Feb 2021/01-14-2021.csv',
 'Jan to Feb 2021/01-15-2021.csv',
 'Jan to Feb 2021/01-16-2021.csv',
 'Jan to Feb 2021/01-17-2021.csv',
 'Jan to Feb 2021/01-18-2021.csv',
 'Jan to Feb 2021/01-19-2021.csv',
 'Jan to Feb 2021/01-20-2021.csv',
 'Jan to Feb 2021/01-21-2021.csv',
 'Jan to Feb 2021/01-22-2021.csv',
 'Jan to Feb 2021/01-23-2021.csv',
 'Jan to Feb 2021/01-24-2021.csv',
 'Jan to Feb 2021/01-25-2021.csv',
 'Jan to Feb 2021/01-26-2021.csv',
 'Jan to Feb 2021/01-27-2021.csv',
 'Jan to Feb 2021/01-28-2021.csv',
 'Jan to Feb 2021/01-29-2021.csv',
 'Jan to Feb 2021/01-30-2021.csv',
 'Jan to Feb 2021/01-31-2021.csv',
 'Jan to Feb 2021/02-01-2021.csv',
 'Jan to Feb 2021/02-02-2021.csv',
 'Jan to Feb 2021/02-03-2021.csv',
 'Jan to Feb 2021/02-04-2021.csv',
 'Jan to Feb 2021/02-05-2021.csv',
 'Jan to Feb 2021/02-06-2021.csv',
 'Jan to Feb 2021/02-07-2021.csv',
 'Jan to Feb 2021/02-08-2021.csv',
 'Jan to Feb 2021/02-09-2021.csv',
 'Jan to Feb 2021/02-10-2021.csv',
 'Jan to Feb 2021/02-11-2021.csv',
 'Jan to Feb 2021/02-12-2021.csv',
 'Jan to Feb 2021/02-13-2021.csv',
 'Jan to Feb 2021/02-14-2021.csv',
 'Jan to Feb 2021/02-15-2021.csv',
 'Jan to Feb 2021/02-16-2021.csv',
 'Jan to Feb 2021/02-17-2021.csv',
 'Jan to Feb 2021/02-18-2021.csv',
 'Jan to Feb 2021/02-19-2021.csv',
 'Jan to Feb 2021/02-20-2021.csv',
 'Jan to Feb 2021/02-21-2021.csv',
 'Jan to Feb 2021/02-22-2021.csv',
 'Jan to Feb 2021/02-23-2021.csv',
 'Jan to Feb 2021/02-24-2021.csv']

In [4]:
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filesnames20+all_filesnames21])
#export to csv
combined_csv.to_csv( "combined_csv.csv", index=False, encoding='utf-8-sig')

us_cases_csv=(combined_csv.to_csv)

In [5]:
#all_filesnames20+all_filesnames21

In [6]:
us_cases_df = pd.read_csv("combined_csv.csv")
us_cases_df.head ()

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,Incident_Rate,People_Tested,People_Hospitalized,Mortality_Rate,UID,ISO3,Testing_Rate,Hospitalization_Rate,Total_Test_Results,Case_Fatality_Ratio
0,Alabama,US,2020-10-02 04:30:36,32.3182,-86.9023,155727,2548,67948.0,85248.0,1.0,3176.384330,1138732.0,NaN,1.636018,84000001.0,USA,23224.332755,NaN,NaN,NaN
1,Alaska,US,2020-10-02 04:30:36,61.3707,-152.4044,7948,57,4838.0,3053.0,2.0,1086.467681,462323.0,NaN,0.717162,84000002.0,USA,63198.162792,NaN,NaN,NaN
2,American Samoa,US,2020-10-02 04:30:36,-14.2710,-170.1320,0,0,NaN,0.0,60.0,0.000000,1571.0,NaN,NaN,16.0,ASM,2823.457522,NaN,NaN,NaN
3,Arizona,US,2020-10-02 04:30:36,33.7298,-111.4312,219212,5674,35411.0,178127.0,4.0,3011.684614,1471368.0,NaN,2.588362,84000004.0,USA,20214.661458,NaN,NaN,NaN
4,Arkansas,US,2020-10-02 04:30:36,34.9697,-92.3731,84821,1384,76186.0,7251.0,5.0,2810.686181,1042616.0,NaN,1.631671,84000005.0,USA,34548.830872,NaN,NaN,NaN

In [11]:
us_cases_df.columns

Index(['Province_State', 'Country_Region', 'Last_Update', 'Lat', 'Long_',
       'Confirmed', 'Deaths', 'Recovered', 'Active', 'FIPS', 'Incident_Rate',
       'People_Tested', 'People_Hospitalized', 'Mortality_Rate', 'UID', 'ISO3',
       'Testing_Rate', 'Hospitalization_Rate', 'Total_Test_Results',
       'Case_Fatality_Ratio'],
      dtype='object')

In [78]:
organized_data_df= us_cases_df [["Province_State","Last_Update","Confirmed","Deaths","Recovered","Active", "People_Tested"]]
organized_data_df.head(100)

,Province_State,Last_Update,Confirmed,Deaths,Recovered,Active,People_Tested
0,Alabama,2020-10-02 04:30:36,155727,2548,67948.0,85248.0,1138732.0
1,Alaska,2020-10-02 04:30:36,7948,57,4838.0,3053.0,462323.0
2,American Samoa,2020-10-02 04:30:36,0,0,NaN,0.0,1571.0
3,Arizona,2020-10-02 04:30:36,219212,5674,35411.0,178127.0,1471368.0
4,Arkansas,2020-10-02 04:30:36,84821,1384,76186.0,7251.0,1042616.0
...,...,...,...,...,...,...,...
95,North Carolina,2020-10-03 04:30:36,214684,3608,184422.0,26654.0,3099704.0
96,North Dakota,2020-10-03 04:30:36,22694,264,18691.0,3739.0,626450.0
97,Northern Mariana Islands,2020-10-03 04:30:36,73,2,29.0,42.0,15185.0
98,Ohio,2020-10-03 04:30:36,156809,5080,135301.0,16603.0,3271748.0
99,Oklahoma,2020-10-03 04:30:36,89559,1044,75753.0,12762.0,1230160.0

In [82]:
organized_data_df[(organized_data_df["Last_Update"]=="2020-10-06 04:30:36")|(organized_data_df["Last_Update"]=="2020-10-1304:30:36 ")|(organized_data_df["Last_Update"]=="2020-10-2004:30:36 ")|(organized_data_df["Last_Update"]=="2020-10-27 04:30:36")|(organized_data_df["Last_Update"]=="2020-11-03 04:30:36")|(organized_data_df["Last_Update"]=="2020-11-10 04:30:36")]|(organized_data_df["Last_Update"]=="2020-11-17 04:30:36")|(organized_data_df["Last_Update"]=="2020-11-24 04:30:36")|(organized_data_df["Last_Update"]=="2020-12-01 04:30:36")|(organized_data_df["Last_Update"]=="2020-12-0804:30:36 ")|(organized_data_df["Last_Update"]=="2020-12-15 04:30:36")|(organized_data_df["Last_Update"]=="2020-12-2204:30:36 ")|(organized_data_df["Last_Update"]=="2020-12-29 04:30:36")|(organized_data_df["Last_Update"]=="2021-01-0504:30:36" )|(organized_data_df["Last_Update"]=="2021-01-12 04:30:36")|(organized_data_df["Last_Update"]=="2021-01-19 04:30:36")|(organized_data_df["Last_Update"]=="2021-01-26 04:30:36")|(organized_data_df["Last_Update"]=="2021-02-02 04:30:36")|(organized_data_df["Last_Update"]=="2021-02-09 04:30:36")|(organized_data_df["Last_Update"]=="2021-02-16 04:30:36")|(organized_data_df["Last_Update"]=="2021-02-2304:30:36")

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]
Index: []

[0 rows x 8533 columns]

In [80]:
organized_data_df[(organized_data_df["Last_Update"]=="2020-10-03 04:30:36")]

,Province_State,Last_Update,Confirmed,Deaths,Recovered,Active,People_Tested
58,Alabama,2020-10-03 04:30:36,157402,2550,67948.0,86200.0,1145601.0
59,Alaska,2020-10-03 04:30:36,8073,57,5042.0,2974.0,469290.0
60,American Samoa,2020-10-03 04:30:36,0,0,NaN,0.0,1616.0
61,Arizona,2020-10-03 04:30:36,219763,5693,35553.0,178517.0,1478504.0
62,Arkansas,2020-10-03 04:30:36,85779,1391,76186.0,8202.0,1054260.0
63,California,2020-10-03 04:30:36,829169,16054,NaN,809959.0,14868431.0
64,Colorado,2020-10-03 04:30:36,71898,2057,6556.0,63263.0,1376920.0
65,Connecticut,2020-10-03 04:30:36,58297,4513,9408.0,44376.0,1676410.0
66,Delaware,2020-10-03 04:30:36,20937,658,10678.0,9617.0,290283.0
67,Diamond Princess,2020-10-03 04:30:36,49,0,NaN,49.0,NaN
68,District of Columbia,2020-10-03 04:30:36,15423,629,12252.0,2542.0,394118.0
69,Florida,2020-10-03 04:30:36,711804,14554,NaN,697250.0,5351521.0
70,Georgia,2020-10-03 04:30:36,320634,7106,NaN,313528.0,2970013.0
71,Grand Princess,2020-10-03 04:30:36,103,3,NaN,100.0,NaN
72,Guam,2020-10-03 04:30:36,2488,49,1887.0,552.0,51118.0
73,Hawaii,2020-10-03 04:30:36,12601,142,10340.0,2119.0,300459.0
74,Idaho,2020-10-03 04:30:36,43238,474,22371.0,20393.0,311337.0
75,Illinois,2020-10-03 04:30:36,300340,8992,NaN,291348.0,5765867.0
76,Indiana,2020-10-03 04:30:36,122640,3681,94816.0,24168.0,1398522.0
77,Iowa,2020-10-03 04:30:36,91482,1377,70501.0,19604.0,775992.0
78,Kansas,2020-10-03 04:30:36,62537,698,2136.0,57644.0,531117.0
79,Kentucky,2020-10-03 04:30:36,70727,1197,12041.0,57489.0,1422520.0
80,Louisiana,2020-10-03 04:30:36,167401,5545,154163.0,7693.0,2357449.0
81,Maine,2020-10-03 04:30:36,5466,141,4741.0,584.0,449290.0
82,Maryland,2020-10-03 04:30:36,126222,3950,7606.0,114666.0,1639785.0
83,Massachusetts,2020-10-03 04:30:36,133631,9490,113768.0,10373.0,4200018.0
84,Michigan,2020-10-03 04:30:36,139996,7110,95051.0,37835.0,3723748.0
85,Minnesota,2020-10-03 04:30:36,101366,2112,90492.0,8762.0,2086963.0
86,Mississippi,2020-10-03 04:30:36,99558,2999,89737.0,6822.0,738401.0
87,Missouri,2020-10-03 04:30:36,131241,2146,NaN,128835.0,1326189.0
88,Montana,2020-10-03 04:30:36,13855,186,9569.0,4100.0,353362.0
89,Nebraska,2020-10-03 04:30:36,46977,493,33820.0,12664.0,464264.0
90,Nevada,2020-10-03 04:30:36,81182,1609,2231.0,77342.0,706635.0
91,New Hampshire,2020-10-03 04:30:36,8534,442,7636.0,456.0,455869.0
92,New Jersey,2020-10-03 04:30:36,212213,16131,34935.0,155563.0,3672127.0
93,New Mexico,2020-10-03 04:30:36,30000,887,16926.0,12187.0,928389.0
94,New York,2020-10-03 04:30:36,464620,33372,76834.0,351596.0,10976024.0
95,North Carolina,2020-10-03 04:30:36,214684,3608,184422.0,26654.0,3099704.0
96,North Dakota,2020-10-03 04:30:36,22694,264,18691.0,3739.0,626450.0
97,Northern Mariana Islands,2020-10-03 04:30:36,73,2,29.0,42.0,15185.0
98,Ohio,2020-10-03 04:30:36,156809,5080,135301.0,16603.0,3271748.0
99,Oklahoma,2020-10-03 04:30:36,89559,1044,75753.0,12762.0,1230160.0
100,Oregon,2020-10-03 04:30:36,34163,563,5738.0,27862.0,697293.0
101,Pennsylvania,2020-10-03 04:30:36,166238,8162,132252.0,25824.0,2066255.0
102,Puerto Rico,2020-10-03 04:30:36,49747,673,NaN,49074.0,355719.0
103,Rhode Island,2020-10-03 04:30:36,25076,1118,2346.0,21612.0,797014.0
104,South Carolina,2020-10-03 04:30:36,149185,3409,72951.0,72825.0,1338052.0
105,South Dakota,2020-10-03 04:30:36,23522,237,19298.0,3987.0,196261.0
106,Tennessee,2020-10-03 04:30:36,198403,2515,182116.0,13772.0,2919014.0
107,Texas,2020-10-03 04:30:36,787698,16501,672144.0,93938.0,6368742.0
108,Utah,2020-10-03 04:30:36,75157,474,56167.0,18516.0,845583.0
109,Vermont,2020-10-03 04:30:36,1768,58,1611.0,99.0,164859.0
110,Virgin Islands,2020-10-03 04:30:36,1326,20,1256.0,50.0,21011.0
111,Virginia,2020-10-03 04:30:36,149687,3250,17752.0,128491.0,2094361.0
112,Washington,2020-10-03 04:30:36,90821,2117,NaN,86667.0,1884074.0
113,West Virginia,2020-10-03 04:30:36,16307,361,11799.0,4147.0,576499.0
114,Wisconsin,2020-10-03 04:30:36,127906,1353,103530.0,23023.0,1580519.0
115,Wyoming,2020-10-03 04:30:36,6214,53,4989.0,1172.0,103278.0

In [67]:

#states = {}
#organized_data_df_ir = organized_data_df.iterrows()
#for index, row in organized_data_df_ir:
#    s = row['Province_State']
#   l = row['Last_Update']
#     if s not in states:
#         states[s] = {
#             'Confirmed' : 0,
#             'Deaths' : 0,
#             'Recovered' : 0,
#             'Active' : 0,
#             'People_Tested' : 0      
#         }
#     else:
#         states[s]['Confirmed'] += float(row['Confirmed'])
#         states[s]['Deaths'] += float(row['Deaths'])
#         states[s]['Recovered'] += float(row['Recovered'])
#         states[s]['Active'] += float(row['Active'])
#         states[s]['People_Tested'] += float(row['People_Tested'])
#     if (int(l.split(' ')[0][-2:]) > 6):
#         break

# dated_states = {}
# dated_states[l] = states
# dated_states
# #start with 7
# states[row['Pr']]

# for index, row in organized_data_df_ir:
#     s = row['Province_State']
#     l = row['Last_Update']
#     if s not in states:
#         states[s] = {
#             'Confirmed' : 0,
#             'Deaths' : 0,
#             'Recovered' : 0,
#             'Active' : 0,
#             'People_Tested' : 0      
#         }
#     else:
#         states[s]['Confirmed'] += float(row['Confirmed'])
#         states[s]['Deaths'] += float(row['Deaths'])
#         states[s]['Recovered'] += float(row['Recovered'])
#         states[s]['Active'] += float(row['Active'])
#         states[s]['People_Tested'] += float(row['People_Tested'])
#     if

{'2020-10-07 04:30:35': {'Alabama': {'Confirmed': 794261.0,
   'Deaths': 12805.0,
   'Recovered': 339740.0,
   'Active': 441892.0,
   'People_Tested': 5804524.0},
  'Alaska': {'Confirmed': 33308.0,
   'Deaths': 231.0,
   'Recovered': 20977.0,
   'Active': 12100.0,
   'People_Tested': 1898738.0},
  'American Samoa': {'Confirmed': 0.0,
   'Deaths': 0.0,
   'Recovered': nan,
   'Active': 0.0,
   'People_Tested': 6464.0},
  'Arizona': {'Confirmed': 881986.0,
   'Deaths': 22811.0,
   'Recovered': 143094.0,
   'Active': 716081.0,
   'People_Tested': 5965653.0},
  'Arkansas': {'Confirmed': 346747.0,
   'Deaths': 5670.0,
   'Recovered': 311368.0,
   'Active': 29709.0,
   'People_Tested': 4270485.0},
  'California': {'Confirmed': 3335794.0,
   'Deaths': 64487.0,
   'Recovered': nan,
   'Active': 3259267.0,
   'People_Tested': 60329287.0},
  'Colorado': {'Confirmed': 291066.0,
   'Deaths': 8254.0,
   'Recovered': 26376.0,
   'Active': 256348.0,
   'People_Tested': 5618142.0},
  'Connecticut': {'Confirmed': 234011.0,
   'Deaths': 18056.0,
   'Recovered': 37632.0,
   'Active': 178323.0,
   'People_Tested': 6755951.0},
  'Delaware': {'Confirmed': 84668.0,
   'Deaths': 2642.0,
   'Recovered': 43112.0,
   'Active': 38979.0,
   'People_Tested': 1172665.0},
  'Diamond Princess': {'Confirmed': 196.0,
   'Deaths': 0.0,
   'Recovered': nan,
   'Active': 196.0,
   'People_Tested': nan},
  'District of Columbia': {'Confirmed': 61962.0,
   'Deaths': 2520.0,
   'Recovered': 49109.0,
   'Active': 10333.0,
   'People_Tested': 1593060.0},
  'Florida': {'Confirmed': 2860728.0,
   'Deaths': 58565.0,
   'Recovered': nan,
   'Active': 2802163.0,
   'People_Tested': 21537537.0},
  'Georgia': {'Confirmed': 1289442.0,
   'Deaths': 28593.0,
   'Recovered': nan,
   'Active': 1260849.0,
   'People_Tested': 12022769.0},
  'Grand Princess': {'Confirmed': 412.0,
   'Deaths': 12.0,
   'Recovered': nan,
   'Active': 400.0,
   'People_Tested': nan},
  'Guam': {'Confirmed': 10475.0,
   'Deaths': 201.0,
   'Recovered': 7556.0,
   'Active': 2718.0,
   'People_Tested': 206995.0},
  'Hawaii': {'Confirmed': 50993.0,
   'Deaths': 608.0,
   'Recovered': 41590.0,
   'Active': 8795.0,
   'People_Tested': 1212933.0},
  'Idaho': {'Confirmed': 175326.0,
   'Deaths': 1923.0,
   'Recovered': 90613.0,
   'Active': 82790.0,
   'People_Tested': 1260316.0},
  'Illinois': {'Confirmed': 1213445.0,
   'Deaths': 36109.0,
   'Recovered': nan,
   'Active': 1177336.0,
   'People_Tested': 23420220.0},
  'Indiana': {'Confirmed': 497821.0,
   'Deaths': 14839.0,
   'Recovered': 386633.0,
   'Active': 96508.0,
   'People_Tested': 5650235.0},
  'Iowa': {'Confirmed': 369787.0,
   'Deaths': 5543.0,
   'Recovered': 285340.0,
   'Active': 78904.0,
   'People_Tested': 3130882.0},
  'Kansas': {'Confirmed': 252811.0,
   'Deaths': 2800.0,
   'Recovered': 8573.0,
   'Active': 232665.0,
   'People_Tested': 2134457.0},
  'Kentucky': {'Confirmed': 288503.0,
   'Deaths': 4825.0,
   'Recovered': 48728.0,
   'Active': 234950.0,
   'People_Tested': 5745346.0},
  'Louisiana': {'Confirmed': 671608.0,
   'Deaths': 22253.0,
   'Recovered': 616652.0,
   'Active': 32703.0,
   'People_Tested': 9489588.0},
  'Maine': {'Confirmed': 22013.0,
   'Deaths': 567.0,
   'Recovered': 19093.0,
   'Active': 2353.0,
   'People_Tested': 1814621.0},
  'Maryland': {'Confirmed': 508122.0,
   'Deaths': 15826.0,
   'Recovered': 30568.0,
   'Active': 461728.0,
   'People_Tested': 6617674.0},
  'Massachusetts': {'Confirmed': 538343.0,
   'Deaths': 38037.0,
   'Recovered': 455072.0,
   'Active': 45234.0,
   'People_Tested': 17171355.0},
  'Michigan': {'Confirmed': 565264.0,
   'Deaths': 28497.0,
   'Recovered': 393614.0,
   'Active': 143153.0,
   'People_Tested': 15071123.0},
  'Minnesota': {'Confirmed': 412778.0,
   'Deaths': 8507.0,
   'Recovered': 369900.0,
   'Active': 34371.0,
   'People_Tested': 8519198.0},
  'Mississippi': {'Confirmed': 400916.0,
   'Deaths': 12036.0,
   'Recovered': 359788.0,
   'Active': 29092.0,
   'People_Tested': 3022100.0},
  'Missouri': {'Confirmed': 534001.0,
   'Deaths': 8658.0,
   'Recovered': nan,
   'Active': 524367.0,
   'People_Tested': 5375158.0},
  'Montana': {'Confirmed': 57693.0,
   'Deaths': 749.0,
   'Recovered': 38416.0,
   'Active': 18528.0,
   'People_Tested': 1435533.0},
  'Nebraska': {'Confirmed': 190446.0,
   'Deaths': 1994.0,
   'Recovered': 136918.0,
   'Active': 51534.0,
   'People_Tested': 1884537.0},
  'Nevada': {'Confirmed': 327427.0,
   'Deaths': 6475.0,
   'Recovered': 8934.0,
   'Active': 312018.0,
   'People_Tested': 2846798.0},
  'New Hampshire': {'Confirmed': 34421.0,
   'Deaths': 1770.0,
   'Recovered': 30656.0,
   'Active': 1995.0,
   'People_Tested': 1843845.0},
  'New Jersey': {'Confirmed': 853926.0,
   'Deaths': 64540.0,
   'Recovered': 140015.0,
   'Active': 626565.0,
   'People_Tested': 14837353.0},
  'New Mexico': {'Confirmed': 121405.0,
   'Deaths': 3563.0,
   'Recovered': 68461.0,
   'Active': 49381.0,
   'People_Tested': 3753247.0},
  'New York': {'Confirmed': 1867460.0,
   'Deaths': 133538.0,
   'Recovered': 308069.0,
   'Active': 1414202.0,
   'People_Tested': 44603959.0},
  'North Carolina': {'Confirmed': 868820.0,
   'Deaths': 14508.0,
   'Recovered': 745910.0,
   'Active': 108402.0,
   'People_Tested': 12590854.0},
  'North Dakota': {'Confirmed': 93240.0,
   'Deaths': 1086.0,
   'Recovered': 77159.0,
   'Active': 14995.0,
   'People_Tested': 2539738.0},
  'Northern Mariana Islands': {'Confirmed': 294.0,
   'Deaths': 8.0,
   'Recovered': 116.0,
   'Active': 170.0,
   'People_Tested': 60751.0},
  'Ohio': {'Confirmed': 633646.0,
   'Deaths': 20431.0,
   'Recovered': 546302.0,
   'Active': 67658.0,
   'People_Tested': 13335384.0},
  'Oklahoma': {'Confirmed': 363037.0,
   'Deaths': 4201.0,
   'Recovered': 308518.0,
   'Active': 50318.0,
   'People_Tested': 4975429.0},
  'Oregon': {'Confirmed': 138493.0,
   'Deaths': 2278.0,
   'Recovered': 23068.0,
   'Active': 113147.0,
   'People_Tested': 2813644.0},
  'Pennsylvania': {'Confirmed': 669703.0,
   'Deaths': 32744.0,
   'Recovered': 533251.0,
   'Active': 103708.0,
   'People_Tested': 8332839.0},
  'Puerto Rico': {'Confirmed': 202102.0,
   'Deaths': 2735.0,
   'Recovered': nan,
   'Active': 199367.0,
   'People_Tested': 1425990.0},
  'Rhode Island': {'Confirmed': 100647.0,
   'Deaths': 4475.0,
   'Recovered': 9419.0,
   'Active': 86753.0,
   'People_Tested': 3211347.0},
  'South Carolina': {'Confirmed': 603817.0,
   'Deaths': 13760.0,
   'Recovered': 294147.0,
   'Active': 295910.0,
   'People_Tested': 5445002.0},
  'South Dakota': {'Confirmed': 96524.0,
   'Deaths': 981.0,
   'Recovered': 78902.0,
   'Active': 16641.0,
   'People_Tested': 794498.0},
  'Tennessee': {'Confirmed': 802907.0,
   'Deaths': 10249.0,
   'Recovered': 735274.0,
   'Active': 57384.0,
   'People_Tested': 11841028.0},
  'Texas': {'Confirmed': 3176075.0,
   'Deaths': 66390.0,
   'Recovered': 2713171.0,
   'Active': 375797.0,
   'People_Tested': 25951243.0},
  'Utah': {'Confirmed': 307723.0,
   'Deaths': 1910.0,
   'Recovered': 228275.0,
   'Active': 77538.0,
   'People_Tested': 3425337.0},
  'Vermont': {'Confirmed': 7148.0,
   'Deaths': 232.0,
   'Recovered': 6474.0,
   'Active': 442.0,
   'People_Tested': 664671.0},
  'Virgin Islands': {'Confirmed': 5302.0,
   'Deaths': 80.0,
   'Recovered': 5042.0,
   'Active': 180.0,
   'People_Tested': 84500.0},
  'Virginia': {'Confirmed': 604917.0,
   'Deaths': 13069.0,
   'Recovered': 71303.0,
   'Active': 519677.0,
   'People_Tested': 8462108.0},
  'Washington': {'Confirmed': 365956.0,
   'Deaths': 8502.0,
   'Recovered': nan,
   'Active': 349794.0,
   'People_Tested': 7648688.0},
  'West Virginia': {'Confirmed': 66172.0,
   'Deaths': 1455.0,
   'Recovered': 47770.0,
   'Active': 16947.0,
   'People_Tested': 2345814.0},
  'Wisconsin': {'Confirmed': 525726.0,
   'Deaths': 5483.0,
   'Recovered': 424278.0,
   'Active': 95965.0,
   'People_Tested': 6395157.0},
  'Wyoming': {'Confirmed': 25712.0,
   'Deaths': 212.0,
   'Recovered': 20504.0,
   'Active': 4996.0,
   'People_Tested': 416437.0}}}

In [66]:
organized_data_df[organized_data_df['Province_State']=='Alabama'].head(10)

,Province_State,Last_Update,Confirmed,Deaths,Recovered,Active,People_Tested
0,Alabama,2020-10-02 04:30:36,155727,2548,67948.0,85248.0,1138732.0
58,Alabama,2020-10-03 04:30:36,157402,2550,67948.0,86200.0,1145601.0
116,Alabama,2020-10-04 04:30:24,158181,2558,67948.0,87874.0,1156045.0
174,Alabama,2020-10-05 04:30:35,158717,2558,67948.0,88663.0,1162518.0
232,Alabama,2020-10-06 04:30:27,159476,2559,67948.0,89206.0,1167513.0
290,Alabama,2020-10-07 04:30:35,160485,2580,67948.0,89949.0,1172847.0
348,Alabama,2020-10-08 04:30:35,161085,2601,67948.0,90869.0,1180818.0
406,Alabama,2020-10-09 04:30:36,162683,2637,71240.0,88098.0,1184710.0
464,Alabama,2020-10-10 04:30:24,163897,2653,71240.0,89572.0,1196452.0
522,Alabama,2020-10-11 04:30:32,164698,2664,71240.0,90622.0,1204320.0

In [18]:
renamed_data_df= organized_data_df.rename(columns=("State":"Province_State","Updated":"Last_Update"))

SyntaxError: invalid syntax (<ipython-input-18-bd136e491477>, line 1)

In [10]:
no_null_us_cases_df = us_cases_df.dropna(how='any')
no_null_us_cases_df.head()

Empty DataFrame
Columns: [Province_State, Country_Region, Last_Update, Lat, Long_, Confirmed, Deaths, Recovered, Active, FIPS, Incident_Rate, People_Tested, People_Hospitalized, Mortality_Rate, UID, ISO3, Testing_Rate, Hospitalization_Rate, Total_Test_Results, Case_Fatality_Ratio]
Index: []

In [ ]:
no_null_us_cases_df.groupby()