In [1]:
import os
import glob
import pandas as pd
#set working directory
#os.chdir("Jan to Feb 2021")

In [2]:
#find all csv files in the folder 
#use glob pattern matching -> extension = 'csv'
#save result in list ->all_filenames

os.chdir("Oct to Dec 2020")
extension = 'csv'
all_filesnames20 = ["Oct to Dec 2020/"+i for i in glob.glob('*.{}'.format(extension))]

all_filesnames20

['Oct to Dec 2020/10-05-2020.csv',
 'Oct to Dec 2020/10-12-2020.csv',
 'Oct to Dec 2020/10-19-2020.csv',
 'Oct to Dec 2020/10-26-2020.csv',
 'Oct to Dec 2020/11-02-2020.csv',
 'Oct to Dec 2020/11-09-2020.csv',
 'Oct to Dec 2020/11-16-2020.csv',
 'Oct to Dec 2020/11-23-2020.csv',
 'Oct to Dec 2020/11-30-2020.csv',
 'Oct to Dec 2020/12-07-2020.csv',
 'Oct to Dec 2020/12-14-2020.csv',
 'Oct to Dec 2020/12-21-2020.csv',
 'Oct to Dec 2020/12-28-2020.csv']

In [3]:
os.chdir("../Jan to Feb 2021")
extension = 'csv'
all_filesnames21 = ["Jan to Feb 2021/"+i for i in glob.glob('*.{}'.format(extension))]

os.chdir("..")

all_filesnames21

['Jan to Feb 2021/01-04-2021.csv',
 'Jan to Feb 2021/01-11-2021.csv',
 'Jan to Feb 2021/01-18-2021.csv',
 'Jan to Feb 2021/01-25-2021.csv',
 'Jan to Feb 2021/02-01-2021.csv',
 'Jan to Feb 2021/02-08-2021.csv',
 'Jan to Feb 2021/02-15-2021.csv',
 'Jan to Feb 2021/02-22-2021.csv']

In [4]:
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filesnames20+all_filesnames21])
#export to csv
combined_csv.to_csv( "combined_csv.csv", index=False, encoding='utf-8-sig')

us_cases_csv=(combined_csv.to_csv)

In [7]:
#all_filesnames20+all_filesnames21

In [5]:
us_cases_df = pd.read_csv("combined_csv.csv")
us_cases_df.head ()

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,Incident_Rate,People_Tested,People_Hospitalized,Mortality_Rate,UID,ISO3,Testing_Rate,Hospitalization_Rate,Total_Test_Results,Case_Fatality_Ratio
0,Alabama,US,2020-10-06 04:30:27,32.3182,-86.9023,159476,2559,67948.0,89206.0,1.0,3257.331714,1167513.0,NaN,1.602249,84000001.0,USA,23811.318561,NaN,NaN,NaN
1,Alaska,US,2020-10-06 04:30:27,61.3707,-152.4044,8613,58,5455.0,3100.0,2.0,1177.371180,479374.0,NaN,0.673401,84000002.0,USA,65528.983179,NaN,NaN,NaN
2,American Samoa,US,2020-10-06 04:30:27,-14.2710,-170.1320,0,0,NaN,0.0,60.0,0.000000,1616.0,NaN,NaN,16.0,ASM,2904.333136,NaN,NaN,NaN
3,Arizona,US,2020-10-06 04:30:27,33.7298,-111.4312,221070,5707,36007.0,179356.0,4.0,3037.211091,1502873.0,NaN,2.581535,84000004.0,USA,20647.498728,NaN,NaN,NaN
4,Arkansas,US,2020-10-06 04:30:27,34.9697,-92.3731,87430,1447,79052.0,6931.0,5.0,2897.139774,1079144.0,NaN,1.655038,84000005.0,USA,35759.247453,NaN,NaN,NaN

In [6]:
us_cases_df.columns

Index(['Province_State', 'Country_Region', 'Last_Update', 'Lat', 'Long_',
       'Confirmed', 'Deaths', 'Recovered', 'Active', 'FIPS', 'Incident_Rate',
       'People_Tested', 'People_Hospitalized', 'Mortality_Rate', 'UID', 'ISO3',
       'Testing_Rate', 'Hospitalization_Rate', 'Total_Test_Results',
       'Case_Fatality_Ratio'],
      dtype='object')

In [7]:
organized_data_df= us_cases_df [["Province_State","Last_Update","Confirmed","Deaths","Recovered","Active", "People_Tested"]]
organized_data_df.head(70)

,Province_State,Last_Update,Confirmed,Deaths,Recovered,Active,People_Tested
0,Alabama,2020-10-06 04:30:27,159476,2559,67948.0,89206.0,1167513.0
1,Alaska,2020-10-06 04:30:27,8613,58,5455.0,3100.0,479374.0
2,American Samoa,2020-10-06 04:30:27,0,0,NaN,0.0,1616.0
3,Arizona,2020-10-06 04:30:27,221070,5707,36007.0,179356.0,1502873.0
4,Arkansas,2020-10-06 04:30:27,87430,1447,79052.0,6931.0,1079144.0
...,...,...,...,...,...,...,...
65,Connecticut,2020-10-13 04:30:36,61377,4532,9522.0,47323.0,1896944.0
66,Delaware,2020-10-13 04:30:36,22289,676,11493.0,10140.0,314281.0
67,Diamond Princess,2020-10-13 04:30:36,49,0,NaN,49.0,NaN
68,District of Columbia,2020-10-13 04:30:36,16022,637,12539.0,2846.0,438819.0
69,Florida,2020-10-13 04:30:36,736024,15412,NaN,720612.0,5567283.0

In [9]:
organized_data_df[(organized_data_df["Last_Update"]=="2020-10-06 04:30:27")|(organized_data_df["Last_Update"]=="2020-10-13 04:30:36 ")|(organized_data_df["Last_Update"]=="2020-10-20 04:30:29 ")|(organized_data_df["Last_Update"]=="2020-10-27 04:30:25")|(organized_data_df["Last_Update"]=="2020-11-03 06:00:57")|(organized_data_df["Last_Update"]=="2020-11-10 04:30:36")]|(organized_data_df["Last_Update"]=="2020-11-17 04:30:36")|(organized_data_df["Last_Update"]=="2020-11-24 04:30:36")|(organized_data_df["Last_Update"]=="2020-12-01 04:30:36")|(organized_data_df["Last_Update"]=="2020-12-0804:30:36 ")|(organized_data_df["Last_Update"]=="2020-12-15 04:30:36")|(organized_data_df["Last_Update"]=="2020-12-2204:30:36 ")|(organized_data_df["Last_Update"]=="2020-12-29 04:30:36")|(organized_data_df["Last_Update"]=="2021-01-0504:30:36" )|(organized_data_df["Last_Update"]=="2021-01-12 04:30:36")|(organized_data_df["Last_Update"]=="2021-01-19 04:30:36")|(organized_data_df["Last_Update"]=="2021-01-26 04:30:36")|(organized_data_df["Last_Update"]=="2021-02-02 04:30:36")|(organized_data_df["Last_Update"]=="2021-02-09 04:30:36")|(organized_data_df["Last_Update"]=="2021-02-16 04:30:36")|(organized_data_df["Last_Update"]=="2021-02-2304:30:36")

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]
Index: []

[0 rows x 1225 columns]

In [8]:
organized_data_df[(organized_data_df["Last_Update"]=="2020-10-06 04:30:27")]

,Province_State,Last_Update,Confirmed,Deaths,Recovered,Active,People_Tested
0,Alabama,2020-10-06 04:30:27,159476,2559,67948.0,89206.0,1167513.0
1,Alaska,2020-10-06 04:30:27,8613,58,5455.0,3100.0,479374.0
2,American Samoa,2020-10-06 04:30:27,0,0,NaN,0.0,1616.0
3,Arizona,2020-10-06 04:30:27,221070,5707,36007.0,179356.0,1502873.0
4,Arkansas,2020-10-06 04:30:27,87430,1447,79052.0,6931.0,1079144.0
5,California,2020-10-06 04:30:27,838480,16171,NaN,819336.0,15301681.0
6,Colorado,2020-10-06 04:30:27,73537,2069,6635.0,64811.0,1430540.0
7,Connecticut,2020-10-06 04:30:27,59120,4517,9408.0,45195.0,1726721.0
8,Delaware,2020-10-06 04:30:27,21363,663,10880.0,9838.0,295835.0
9,Diamond Princess,2020-10-06 04:30:27,49,0,NaN,49.0,NaN
10,District of Columbia,2020-10-06 04:30:27,15547,631,12306.0,2610.0,401568.0
11,Florida,2020-10-06 04:30:27,717874,14712,NaN,703162.0,5412683.0
12,Georgia,2020-10-06 04:30:27,323714,7192,NaN,316522.0,3032757.0
13,Grand Princess,2020-10-06 04:30:27,103,3,NaN,100.0,NaN
14,Guam,2020-10-06 04:30:27,2753,54,1895.0,804.0,52365.0
15,Hawaii,2020-10-06 04:30:27,12854,157,10446.0,2251.0,306112.0
16,Idaho,2020-10-06 04:30:27,44422,487,22930.0,21005.0,318167.0
17,Illinois,2020-10-06 04:30:27,306088,9054,NaN,297034.0,5927695.0
18,Indiana,2020-10-06 04:30:27,125976,3733,98127.0,24168.0,1425175.0
19,Iowa,2020-10-06 04:30:27,93260,1398,71920.0,19942.0,788014.0
20,Kansas,2020-10-06 04:30:27,63979,706,2165.0,58968.0,541106.0
21,Kentucky,2020-10-06 04:30:27,73158,1214,12445.0,59499.0,1453778.0
22,Louisiana,2020-10-06 04:30:27,168512,5586,154163.0,8763.0,2391020.0
23,Maine,2020-10-06 04:30:27,5544,142,4807.0,595.0,466682.0
24,Maryland,2020-10-06 04:30:27,127791,3961,7657.0,116173.0,1668317.0
25,Massachusetts,2020-10-06 04:30:27,135462,9530,113768.0,12164.0,4371050.0
26,Michigan,2020-10-06 04:30:27,142726,7139,99521.0,36066.0,3818827.0
27,Minnesota,2020-10-06 04:30:27,104799,2136,94416.0,8247.0,2169786.0
28,Mississippi,2020-10-06 04:30:27,100703,3013,90577.0,7113.0,805358.0
29,Missouri,2020-10-06 04:30:27,135604,2175,NaN,133186.0,1358668.0
30,Montana,2020-10-06 04:30:27,14847,190,9649.0,5008.0,369975.0
31,Nebraska,2020-10-06 04:30:27,48259,503,34613.0,13143.0,476952.0
32,Nevada,2020-10-06 04:30:27,82437,1623,2241.0,78573.0,716564.0
33,New Hampshire,2020-10-06 04:30:27,8645,443,7710.0,492.0,465878.0
34,New Jersey,2020-10-06 04:30:27,214540,16138,35070.0,157505.0,3758058.0
35,New Mexico,2020-10-06 04:30:27,30632,894,17270.0,12468.0,947945.0
36,New York,2020-10-06 04:30:27,468840,33402,77141.0,355160.0,11297024.0
37,North Carolina,2020-10-06 04:30:27,219754,3637,192644.0,23473.0,3193916.0
38,North Dakota,2020-10-06 04:30:27,23862,277,19892.0,3693.0,642669.0
39,Northern Mariana Islands,2020-10-06 04:30:27,75,2,29.0,44.0,15196.0
40,Ohio,2020-10-06 04:30:27,159964,5136,137633.0,17400.0,3388186.0
41,Oklahoma,2020-10-06 04:30:27,91982,1055,78155.0,12772.0,1249056.0
42,Oregon,2020-10-06 04:30:27,35049,572,5826.0,28651.0,709012.0
43,Pennsylvania,2020-10-06 04:30:27,169101,8207,134649.0,26245.0,2105159.0
44,Puerto Rico,2020-10-06 04:30:27,51305,695,NaN,50610.0,357277.0
45,Rhode Island,2020-10-06 04:30:27,25419,1121,2381.0,21917.0,820305.0
46,South Carolina,2020-10-06 04:30:27,152159,3456,74272.0,74431.0,1389106.0
47,South Dakota,2020-10-06 04:30:27,24598,248,20076.0,4274.0,200443.0
48,Tennessee,2020-10-06 04:30:27,203699,2597,185221.0,15881.0,3014664.0
49,Texas,2020-10-06 04:30:27,799793,16717,683700.0,94182.0,6571677.0
50,Utah,2020-10-06 04:30:27,78723,482,57965.0,20276.0,866180.0
51,Vermont,2020-10-06 04:30:27,1817,58,1625.0,134.0,167506.0
52,Virgin Islands,2020-10-06 04:30:27,1322,20,1265.0,37.0,21239.0
53,Virginia,2020-10-06 04:30:27,152557,3276,17893.0,131156.0,2139991.0
54,Washington,2020-10-06 04:30:27,92136,2135,NaN,88118.0,1935899.0
55,West Virginia,2020-10-06 04:30:27,16749,367,12051.0,4331.0,596531.0
56,Wisconsin,2020-10-06 04:30:27,134359,1381,108371.0,24607.0,1614232.0
57,Wyoming,2020-10-06 04:30:27,6629,53,5272.0,1304.0,106162.0

In [67]:

#states = {}
#organized_data_df_ir = organized_data_df.iterrows()
#for index, row in organized_data_df_ir:
#    s = row['Province_State']
#   l = row['Last_Update']
#     if s not in states:
#         states[s] = {
#             'Confirmed' : 0,
#             'Deaths' : 0,
#             'Recovered' : 0,
#             'Active' : 0,
#             'People_Tested' : 0      
#         }
#     else:
#         states[s]['Confirmed'] += float(row['Confirmed'])
#         states[s]['Deaths'] += float(row['Deaths'])
#         states[s]['Recovered'] += float(row['Recovered'])
#         states[s]['Active'] += float(row['Active'])
#         states[s]['People_Tested'] += float(row['People_Tested'])
#     if (int(l.split(' ')[0][-2:]) > 6):
#         break

# dated_states = {}
# dated_states[l] = states
# dated_states
# #start with 7
# states[row['Pr']]

# for index, row in organized_data_df_ir:
#     s = row['Province_State']
#     l = row['Last_Update']
#     if s not in states:
#         states[s] = {
#             'Confirmed' : 0,
#             'Deaths' : 0,
#             'Recovered' : 0,
#             'Active' : 0,
#             'People_Tested' : 0      
#         }
#     else:
#         states[s]['Confirmed'] += float(row['Confirmed'])
#         states[s]['Deaths'] += float(row['Deaths'])
#         states[s]['Recovered'] += float(row['Recovered'])
#         states[s]['Active'] += float(row['Active'])
#         states[s]['People_Tested'] += float(row['People_Tested'])
#     if

{'2020-10-07 04:30:35': {'Alabama': {'Confirmed': 794261.0,
   'Deaths': 12805.0,
   'Recovered': 339740.0,
   'Active': 441892.0,
   'People_Tested': 5804524.0},
  'Alaska': {'Confirmed': 33308.0,
   'Deaths': 231.0,
   'Recovered': 20977.0,
   'Active': 12100.0,
   'People_Tested': 1898738.0},
  'American Samoa': {'Confirmed': 0.0,
   'Deaths': 0.0,
   'Recovered': nan,
   'Active': 0.0,
   'People_Tested': 6464.0},
  'Arizona': {'Confirmed': 881986.0,
   'Deaths': 22811.0,
   'Recovered': 143094.0,
   'Active': 716081.0,
   'People_Tested': 5965653.0},
  'Arkansas': {'Confirmed': 346747.0,
   'Deaths': 5670.0,
   'Recovered': 311368.0,
   'Active': 29709.0,
   'People_Tested': 4270485.0},
  'California': {'Confirmed': 3335794.0,
   'Deaths': 64487.0,
   'Recovered': nan,
   'Active': 3259267.0,
   'People_Tested': 60329287.0},
  'Colorado': {'Confirmed': 291066.0,
   'Deaths': 8254.0,
   'Recovered': 26376.0,
   'Active': 256348.0,
   'People_Tested': 5618142.0},
  'Connecticut': {'Confirmed': 234011.0,
   'Deaths': 18056.0,
   'Recovered': 37632.0,
   'Active': 178323.0,
   'People_Tested': 6755951.0},
  'Delaware': {'Confirmed': 84668.0,
   'Deaths': 2642.0,
   'Recovered': 43112.0,
   'Active': 38979.0,
   'People_Tested': 1172665.0},
  'Diamond Princess': {'Confirmed': 196.0,
   'Deaths': 0.0,
   'Recovered': nan,
   'Active': 196.0,
   'People_Tested': nan},
  'District of Columbia': {'Confirmed': 61962.0,
   'Deaths': 2520.0,
   'Recovered': 49109.0,
   'Active': 10333.0,
   'People_Tested': 1593060.0},
  'Florida': {'Confirmed': 2860728.0,
   'Deaths': 58565.0,
   'Recovered': nan,
   'Active': 2802163.0,
   'People_Tested': 21537537.0},
  'Georgia': {'Confirmed': 1289442.0,
   'Deaths': 28593.0,
   'Recovered': nan,
   'Active': 1260849.0,
   'People_Tested': 12022769.0},
  'Grand Princess': {'Confirmed': 412.0,
   'Deaths': 12.0,
   'Recovered': nan,
   'Active': 400.0,
   'People_Tested': nan},
  'Guam': {'Confirmed': 10475.0,
   'Deaths': 201.0,
   'Recovered': 7556.0,
   'Active': 2718.0,
   'People_Tested': 206995.0},
  'Hawaii': {'Confirmed': 50993.0,
   'Deaths': 608.0,
   'Recovered': 41590.0,
   'Active': 8795.0,
   'People_Tested': 1212933.0},
  'Idaho': {'Confirmed': 175326.0,
   'Deaths': 1923.0,
   'Recovered': 90613.0,
   'Active': 82790.0,
   'People_Tested': 1260316.0},
  'Illinois': {'Confirmed': 1213445.0,
   'Deaths': 36109.0,
   'Recovered': nan,
   'Active': 1177336.0,
   'People_Tested': 23420220.0},
  'Indiana': {'Confirmed': 497821.0,
   'Deaths': 14839.0,
   'Recovered': 386633.0,
   'Active': 96508.0,
   'People_Tested': 5650235.0},
  'Iowa': {'Confirmed': 369787.0,
   'Deaths': 5543.0,
   'Recovered': 285340.0,
   'Active': 78904.0,
   'People_Tested': 3130882.0},
  'Kansas': {'Confirmed': 252811.0,
   'Deaths': 2800.0,
   'Recovered': 8573.0,
   'Active': 232665.0,
   'People_Tested': 2134457.0},
  'Kentucky': {'Confirmed': 288503.0,
   'Deaths': 4825.0,
   'Recovered': 48728.0,
   'Active': 234950.0,
   'People_Tested': 5745346.0},
  'Louisiana': {'Confirmed': 671608.0,
   'Deaths': 22253.0,
   'Recovered': 616652.0,
   'Active': 32703.0,
   'People_Tested': 9489588.0},
  'Maine': {'Confirmed': 22013.0,
   'Deaths': 567.0,
   'Recovered': 19093.0,
   'Active': 2353.0,
   'People_Tested': 1814621.0},
  'Maryland': {'Confirmed': 508122.0,
   'Deaths': 15826.0,
   'Recovered': 30568.0,
   'Active': 461728.0,
   'People_Tested': 6617674.0},
  'Massachusetts': {'Confirmed': 538343.0,
   'Deaths': 38037.0,
   'Recovered': 455072.0,
   'Active': 45234.0,
   'People_Tested': 17171355.0},
  'Michigan': {'Confirmed': 565264.0,
   'Deaths': 28497.0,
   'Recovered': 393614.0,
   'Active': 143153.0,
   'People_Tested': 15071123.0},
  'Minnesota': {'Confirmed': 412778.0,
   'Deaths': 8507.0,
   'Recovered': 369900.0,
   'Active': 34371.0,
   'People_Tested': 8519198.0},
  'Mississippi': {'Confirmed': 400916.0,
   'Deaths': 12036.0,
   'Recovered': 359788.0,
   'Active': 29092.0,
   'People_Tested': 3022100.0},
  'Missouri': {'Confirmed': 534001.0,
   'Deaths': 8658.0,
   'Recovered': nan,
   'Active': 524367.0,
   'People_Tested': 5375158.0},
  'Montana': {'Confirmed': 57693.0,
   'Deaths': 749.0,
   'Recovered': 38416.0,
   'Active': 18528.0,
   'People_Tested': 1435533.0},
  'Nebraska': {'Confirmed': 190446.0,
   'Deaths': 1994.0,
   'Recovered': 136918.0,
   'Active': 51534.0,
   'People_Tested': 1884537.0},
  'Nevada': {'Confirmed': 327427.0,
   'Deaths': 6475.0,
   'Recovered': 8934.0,
   'Active': 312018.0,
   'People_Tested': 2846798.0},
  'New Hampshire': {'Confirmed': 34421.0,
   'Deaths': 1770.0,
   'Recovered': 30656.0,
   'Active': 1995.0,
   'People_Tested': 1843845.0},
  'New Jersey': {'Confirmed': 853926.0,
   'Deaths': 64540.0,
   'Recovered': 140015.0,
   'Active': 626565.0,
   'People_Tested': 14837353.0},
  'New Mexico': {'Confirmed': 121405.0,
   'Deaths': 3563.0,
   'Recovered': 68461.0,
   'Active': 49381.0,
   'People_Tested': 3753247.0},
  'New York': {'Confirmed': 1867460.0,
   'Deaths': 133538.0,
   'Recovered': 308069.0,
   'Active': 1414202.0,
   'People_Tested': 44603959.0},
  'North Carolina': {'Confirmed': 868820.0,
   'Deaths': 14508.0,
   'Recovered': 745910.0,
   'Active': 108402.0,
   'People_Tested': 12590854.0},
  'North Dakota': {'Confirmed': 93240.0,
   'Deaths': 1086.0,
   'Recovered': 77159.0,
   'Active': 14995.0,
   'People_Tested': 2539738.0},
  'Northern Mariana Islands': {'Confirmed': 294.0,
   'Deaths': 8.0,
   'Recovered': 116.0,
   'Active': 170.0,
   'People_Tested': 60751.0},
  'Ohio': {'Confirmed': 633646.0,
   'Deaths': 20431.0,
   'Recovered': 546302.0,
   'Active': 67658.0,
   'People_Tested': 13335384.0},
  'Oklahoma': {'Confirmed': 363037.0,
   'Deaths': 4201.0,
   'Recovered': 308518.0,
   'Active': 50318.0,
   'People_Tested': 4975429.0},
  'Oregon': {'Confirmed': 138493.0,
   'Deaths': 2278.0,
   'Recovered': 23068.0,
   'Active': 113147.0,
   'People_Tested': 2813644.0},
  'Pennsylvania': {'Confirmed': 669703.0,
   'Deaths': 32744.0,
   'Recovered': 533251.0,
   'Active': 103708.0,
   'People_Tested': 8332839.0},
  'Puerto Rico': {'Confirmed': 202102.0,
   'Deaths': 2735.0,
   'Recovered': nan,
   'Active': 199367.0,
   'People_Tested': 1425990.0},
  'Rhode Island': {'Confirmed': 100647.0,
   'Deaths': 4475.0,
   'Recovered': 9419.0,
   'Active': 86753.0,
   'People_Tested': 3211347.0},
  'South Carolina': {'Confirmed': 603817.0,
   'Deaths': 13760.0,
   'Recovered': 294147.0,
   'Active': 295910.0,
   'People_Tested': 5445002.0},
  'South Dakota': {'Confirmed': 96524.0,
   'Deaths': 981.0,
   'Recovered': 78902.0,
   'Active': 16641.0,
   'People_Tested': 794498.0},
  'Tennessee': {'Confirmed': 802907.0,
   'Deaths': 10249.0,
   'Recovered': 735274.0,
   'Active': 57384.0,
   'People_Tested': 11841028.0},
  'Texas': {'Confirmed': 3176075.0,
   'Deaths': 66390.0,
   'Recovered': 2713171.0,
   'Active': 375797.0,
   'People_Tested': 25951243.0},
  'Utah': {'Confirmed': 307723.0,
   'Deaths': 1910.0,
   'Recovered': 228275.0,
   'Active': 77538.0,
   'People_Tested': 3425337.0},
  'Vermont': {'Confirmed': 7148.0,
   'Deaths': 232.0,
   'Recovered': 6474.0,
   'Active': 442.0,
   'People_Tested': 664671.0},
  'Virgin Islands': {'Confirmed': 5302.0,
   'Deaths': 80.0,
   'Recovered': 5042.0,
   'Active': 180.0,
   'People_Tested': 84500.0},
  'Virginia': {'Confirmed': 604917.0,
   'Deaths': 13069.0,
   'Recovered': 71303.0,
   'Active': 519677.0,
   'People_Tested': 8462108.0},
  'Washington': {'Confirmed': 365956.0,
   'Deaths': 8502.0,
   'Recovered': nan,
   'Active': 349794.0,
   'People_Tested': 7648688.0},
  'West Virginia': {'Confirmed': 66172.0,
   'Deaths': 1455.0,
   'Recovered': 47770.0,
   'Active': 16947.0,
   'People_Tested': 2345814.0},
  'Wisconsin': {'Confirmed': 525726.0,
   'Deaths': 5483.0,
   'Recovered': 424278.0,
   'Active': 95965.0,
   'People_Tested': 6395157.0},
  'Wyoming': {'Confirmed': 25712.0,
   'Deaths': 212.0,
   'Recovered': 20504.0,
   'Active': 4996.0,
   'People_Tested': 416437.0}}}

In [66]:
organized_data_df[organized_data_df['Province_State']=='Alabama'].head(10)

,Province_State,Last_Update,Confirmed,Deaths,Recovered,Active,People_Tested
0,Alabama,2020-10-02 04:30:36,155727,2548,67948.0,85248.0,1138732.0
58,Alabama,2020-10-03 04:30:36,157402,2550,67948.0,86200.0,1145601.0
116,Alabama,2020-10-04 04:30:24,158181,2558,67948.0,87874.0,1156045.0
174,Alabama,2020-10-05 04:30:35,158717,2558,67948.0,88663.0,1162518.0
232,Alabama,2020-10-06 04:30:27,159476,2559,67948.0,89206.0,1167513.0
290,Alabama,2020-10-07 04:30:35,160485,2580,67948.0,89949.0,1172847.0
348,Alabama,2020-10-08 04:30:35,161085,2601,67948.0,90869.0,1180818.0
406,Alabama,2020-10-09 04:30:36,162683,2637,71240.0,88098.0,1184710.0
464,Alabama,2020-10-10 04:30:24,163897,2653,71240.0,89572.0,1196452.0
522,Alabama,2020-10-11 04:30:32,164698,2664,71240.0,90622.0,1204320.0

In [18]:
renamed_data_df= organized_data_df.rename(columns=("State":"Province_State","Updated":"Last_Update"))

SyntaxError: invalid syntax (<ipython-input-18-bd136e491477>, line 1)

In [10]:
no_null_us_cases_df = us_cases_df.dropna(how='any')
no_null_us_cases_df.head()

Empty DataFrame
Columns: [Province_State, Country_Region, Last_Update, Lat, Long_, Confirmed, Deaths, Recovered, Active, FIPS, Incident_Rate, People_Tested, People_Hospitalized, Mortality_Rate, UID, ISO3, Testing_Rate, Hospitalization_Rate, Total_Test_Results, Case_Fatality_Ratio]
Index: []

In [ ]:
no_null_us_cases_df.groupby()